services:
  - type: web
    name: fikstur-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: master
    healthCheckPath: /
    numInstances: 1
