services:
  - type: web
    name: fikstur-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: master
    healthCheckPath: /health
    numInstances: 1
